### ISSUE TITLE
Temporary Hosting

### ISSUE THREAD

**Issue by VottonDev** [Pomfe/pomfe.co-v1#11]
Feature todo: Temporary Hosting (File Expiry)

Basically, the idea is that you can choose when the file gets deleted if you don't want the file to remain permanently on the website.

**Comment by Derewith** [comment]
great feature!

**Comment by Rithari** [comment]
+Support

**Comment by ZythVX** [comment]
This will have to wait until PomfePanel.
Anyways, yeah +support

**Comment by ZythVX** [comment]
**This will be coming to PomfePanel Phase 2**
